import React from 'react';
import { Menu, RefreshCw, Bell } from 'lucide-react';

const CareStaffHeader = ({ p }: { p: any }) => {
    const {
        activeTab,
        allCourses,
        allDepartments,
        applicantsList,
        applications,
        appStatusData,
        attendeeCourseFilter,
        attendeeFilter,
        attendees,
        attendeeSectionFilter,
        commandHubTab,
        completionForm,
        confirmDeleteEvent,
        confirmDeleteStudent,
        counselingReqs,
        counselingTab,
        createEvent,
        downloadCSV,
        editForm,
        editingEventId,
        eventFilter,
        events,
        eventToDelete,
        feedbackList,
        fetchCounseling,
        fetchData,
        formModalView,
        functions,
        getCurrentLocation,
        handleAddScholarship,
        handleAppAction,
        handleCompleteSession,
        handleDeleteApplication,
        handleDeleteEvent,
        handleDeleteScholarship,
        handleDownloadReferralForm,
        handleEditEvent,
        handleExportApplicants,
        handleFinalizeSupport,
        handleForwardSupport,
        handlePrintSupport,
        handleResetSystem,
        handleScheduleSubmit,
        handleUpdateStudent,
        handleViewApplicants,
        handleViewAttendees,
        handleViewFeedback,
        handleViewProfile,
        isAuthenticated,
        isRefreshing,
        loading,
        logAudit,
        logout,
        navigate,
        newEvent,
        notifications,
        openEditModal,
        openSupportModal,
        processSupportRequest,
        refreshAll,
        renderDetailedDescription,
        scheduleData,
        scholarshipForm,
        scholarships,
        searchTerm,
        selectedApp,
        selectedEventTitle,
        selectedScholarship,
        selectedStudent,
        selectedSupportReq,
        session,
        setActiveTab,
        setAllCourses,
        setAllDepartments,
        setApplicantsList,
        setApplications,
        setAttendeeCourseFilter,
        setAttendeeFilter,
        setAttendees,
        setAttendeeSectionFilter,
        setCommandHubTab,
        setCompletionForm,
        setCounselingReqs,
        setCounselingTab,
        setEditForm,
        setEditingEventId,
        setEventFilter,
        setEvents,
        setEventToDelete,
        setFeedbackList,
        setFormModalView,
        setIsRefreshing,
        setLoading,
        setNewEvent,
        setNotifications,
        setScheduleData,
        setScholarshipForm,
        setScholarships,
        setSearchTerm,
        setSelectedApp,
        setSelectedEventTitle,
        setSelectedScholarship,
        setSelectedStudent,
        setSelectedSupportReq,
        setShowApplicantModal,
        setShowApplicationModal,
        setShowAttendeesModal,
        setShowCommandHub,
        setShowCompleteModal,
        setShowCounselingFormModal,
        setShowDeleteEventModal,
        setShowDeleteModal,
        setShowEditModal,
        setShowEventModal,
        setShowFeedbackModal,
        setShowResetModal,
        setShowScheduleModal,
        setShowScholarshipModal,
        setShowSupportModal,
        setSidebarOpen,
        setStaffNotes,
        setStatusFilter,
        setStudents,
        setStudentToDelete,
        setSupportCategory,
        setSupportForm,
        setSupportReqs,
        setSupportTab,
        setToast,
        setViewFormReq,
        setYearLevelFilter,
        sharedState,
        showApplicantModal,
        showApplicationModal,
        showAttendeesModal,
        showCommandHub,
        showCompleteModal,
        showCounselingFormModal,
        showDeleteEventModal,
        showDeleteModal,
        showEditModal,
        showEventModal,
        showFeedbackModal,
        showResetModal,
        showScheduleModal,
        showScholarshipModal,
        showSupportModal,
        showToastMessage,
        sidebarOpen,
        staffNotes,
        stats,
        statusFilter,
        students,
        studentToDelete,
        supportCategory,
        supportForm,
        supportReqs,
        supportTab,
        toast,
        viewFormReq,
        yearLevelFilter
    } = p;

    return (
                <header className="h-16 glass gradient-border flex items-center justify-between px-6 lg:px-10 relative z-10">
                    <div className="flex items-center gap-4">
                        <button onClick={() => setSidebarOpen(true)} className="lg:hidden p-2 text-gray-500 hover:text-purple-600 hover:bg-purple-50 rounded-lg transition-all"><Menu /></button>
                        <h2 className="text-xl font-bold gradient-text capitalize">{activeTab}</h2>
                    </div>
                    <div className="flex items-center gap-3">
                        <button onClick={refreshAll} disabled={isRefreshing} title="Refresh Dashboard" className="w-10 h-10 rounded-xl bg-white/80 flex items-center justify-center text-gray-500 hover:text-purple-600 hover:shadow-md transition-all border border-gray-100 disabled:opacity-50">
                            <RefreshCw size={18} className={isRefreshing ? 'animate-spin' : ''} />
                        </button>
                        <button className="w-10 h-10 rounded-xl bg-white/80 flex items-center justify-center text-gray-500 hover:text-purple-600 hover:shadow-md transition-all relative border border-gray-100">
                            <Bell size={20} />
                            {notifications.length > 0 && <span className="absolute -top-1 -right-1 w-3 h-3 bg-red-500 rounded-full border-2 border-white animate-pulse-glow" />}
                        </button>
                    </div>
                </header>
    );
};

export default CareStaffHeader;

